### ISSUE TITLE
Error with VCD file

### ISSUE THREAD

**Issue by StevenGroom** [yne/vcd#17]
vcd-windows-latest-clang.exe < counter\waves.vcd

Fatal error. Send your VCD at https://github.com/yne/vcd/issue

Reason: MAX_CHANNEL reached (400), rebuild with -DMAX_CHANNEL=...

VCD File below :

$date
  2022-03-12T16:14:46.339792
$end
$version
  ROHD v0.2.0
$end
$comment
  Generated by ROHD - www.github.com/intel/rohd
$end
$timescale 1ps $end
$scope module counter $end
  $var wire 1 s0 en $end
  $var wire 1 s1 reset $end
  $var wire 1 s2 clk $end
  $var wire 8 s3 val $end
  $var wire 8 s4 s0 $end
  $var wire 8 s5 nextVal $end
  $scope module sequential $end
    $var wire 1 s6 _in0_reset $end
    $var wire 8 s7 _in1_s0 $end
    $var wire 1 s8 _in2_en $end
    $var wire 8 s9 _in3_nextVal $end
    $var wire 1 s10 _clk0_clk $end
    $var wire 8 s11 _out4_val $end
  $upscope $end
$upscope $end
$enddefinitions $end
$dumpvars
zs0
zs1
0s2
bzzzzzzzz s3
b00000000 s4
bxxxxxxxx s5
zs6
b00000000 s7
zs8
bxxxxxxxx s9
0s10
bzzzzzzzz s11
$end
#0
0s0
1s1
1s6
0s8
#5
1s2
b00000000 s3
b00000001 s5
b00000001 s9
1s10
b00000000 s11
#10
0s2
0s10
#15
1s2
1s10
#20
0s2
0s10
#25
0s1
1s2
0s6
1s10
#30
0s2
0s10
#35
1s2
1s10
#40
0s2
0s10
#45
1s0
1s2
b00000001 s3
b00000010 s5
1s8
b00000010 s9
1s10
b00000001 s11
#50
0s2
0s10
#55
1s2
b00000010 s3
b00000011 s5
b00000011 s9
1s10
b00000010 s11
#60
0s2
0s10
#65
1s2
b00000011 s3
b00000100 s5
b00000100 s9
1s10
b00000011 s11
#70
0s2
0s10
#75
1s2
b00000100 s3
b00000101 s5
b00000101 s9
1s10
b00000100 s11
#80
0s2
0s10
#85
1s2
b00000101 s3
b00000110 s5
b00000110 s9
1s10
b00000101 s11
#90
0s2
0s10
#95
1s2
b00000110 s3
b00000111 s5
b00000111 s9
1s10
b00000110 s11
#100
0s2
0s10

**Comment by yne** [comment]
Fixed by https://github.com/yne/vcd/commit/f2b1627c6bf2f3ba8f4c379205a205085fc5f742

funny stuff in ROHD vcd files:
- ids are not base94
- values exist before `#0` timestamp

```yml
global:
  zoom: 3
  date: 2022-03-12T16:14:46.339792
  total: 21
  skip: 0
  time:
    scale: 1.00
    unit: ps 
    line         : "0                             10                            20                            "
channels:
  counter:
    en           : "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁╱▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔"
    reset        : "▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔╲▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁"
    clk          : "▁▁▁╱▔▔╲▁▁╱▔▔╲▁▁╱▔▔╲▁▁╱▔▔╲▁▁╱▔▔╲▁▁╱▔▔╲▁▁╱▔▔╲▁▁╱▔▔╲▁▁╱▔▔╲▁▁╱▔▔╲▁▁"
    val          : "0  0  0  0  0  0  0  0  0  1  1  2  2  3  3  4  4  5  5  6  6  "
    s0           : "0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  "
    nextVal      : "0  1  1  1  1  1  1  1  1  2  2  3  3  4  4  5  5  6  6  7  7  "
  sequential:
    _in0_reset   : "▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔╲▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁"
    _in1_s0      : "0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  "
    _in2_en      : "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁╱▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔"
    _in3_nextVal : "0  1  1  1  1  1  1  1  1  2  2  3  3  4  4  5  5  6  6  7  7  "
    _clk0_clk    : "▁▁▁╱▔▔╲▁▁╱▔▔╲▁▁╱▔▔╲▁▁╱▔▔╲▁▁╱▔▔╲▁▁╱▔▔╲▁▁╱▔▔╲▁▁╱▔▔╲▁▁╱▔▔╲▁▁╱▔▔╲▁▁"
    _out4_val    : "0  0  0  0  0  0  0  0  0  1  1  2  2  3  3  4  4  5  5  6  6  "
```

Thanks for the report :+1:
